# Generated by Django 2.2.2 on 2019-06-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=30)),
                ('sentiment', models.CharField(max_length=30)),
                ('score', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
