# Generated by Django 2.2.2 on 2019-06-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='score',
            field=models.FloatField(max_length=30),
        ),
    ]
